# Generated by Django 5.0 on 2024-02-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_member_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlterUser',
        ),
    ]
